before_script:
    - rustc --version
    
build:
    stage: build
    script:
        - cargo build

test:
    stage: test
    script:
        - cargo test
        - kcov target/cov target/debug/motion_of_confidence-*
        - COVERAGE=$(grep -Po 'covered":.*?[^\\]"' target/cov/index.json | grep "[0-9]*\.[0-9]" -o)
        - echo "Coverage:" $COVERAGE
