[package]
name = "bookmarkt"
version = "0.1.0"
authors = ["team-chiru <team-chiru@protonmail.com>"]


[dependencies]
rusqlite = "0.6"
chrono = "*"
yaml-rust = "*"
regex = "*"
log="*"
env_logger="*"
treexml = "0.2"
serde_json = "0.9.9"
