[package]
name = "bookmarkt"
version = "0.1.0"
authors = ["team-chiru <team-chiru@protonmail.com>"]

[dependencies]
rusqlite = "*"
chrono = "*"
yaml-rust = "*"
toml = "*"
regex = "*"
log="*"
env_logger="*"
dotenv = "*"

custom_derive="*"
derive_builder="*"
