[package]
name = "bookmarkt"
version = "0.1.0"
authors = ["team-chiru <team-chiru@protonmail.com>"]

[dependencies]
rusqlite = "0.6"
chrono = "*"
yaml-rust = "*"
toml = "*"
regex = "*"
log="*"
env_logger="*"

iron="*"
unicase="*"
params="*"

serde = "*"
serde_derive="*"
serde_json="*"
